{% set name = "docutils" %}
{% set version = "0.20" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/docutils-{{ version }}.tar.gz
  sha256: f75a5a52fbcacd81b47e42888ad2b380748aaccfb3f13af0fe69deb759f01eb6

build:
  number: 0
  skip: true  # [py<36]
  # cannot be noarch b/c of scripts
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - docutils
    - docutils.languages
    - docutils.parsers
    - docutils.parsers.rst
    - docutils.parsers.rst.directives
    - docutils.parsers.rst.languages
    - docutils.readers
    - docutils.transforms
    - docutils.utils
    - docutils.utils.math
    - docutils.writers
    - docutils.writers.html4css1
    - docutils.writers.html5_polyglot
    - docutils.writers.latex2e
    - docutils.writers.odf_odt
    - docutils.writers.pep_html
    - docutils.writers.s5_html
    - docutils.writers.xetex
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://docutils.sourceforge.net/
  license: LicenseRef-Public-Domain-Dedictation and BSD-2-Clause and LicenseRef-PSF-2.1.1 and GPL-3.0-or-later
  license_file: COPYING.txt
  summary: Docutils -- Python Documentation Utilities
  description: |
    Docutils is an open-source text processing system for processing plaintext
    documentation into useful formats, such as HTML, LaTeX, man-pages, open-
    document, or XML.
  doc_url: http://docutils.sourceforge.net/docs/index.html
  doc_source_url: https://sourceforge.net/p/docutils/code/HEAD/tree/trunk/docutils/docs/index.txt
  dev_url: http://svn.code.sf.net/p/docutils/code

extra:
  recipe-maintainers:
    - nehaljwani
    - ocefpaf
